---
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    uses: neticdk/shared-github-actions/.github/workflows/go-ci.yaml@main
  debug:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        if: inputs.go-version == ''
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Check go mod tidy
        run: |
          go mod tidy
          echo $(git diff go.mod go.sum)
          if git diff --exit-code go.mod go.sum; then
            echo "go.mod and go.sum are tidy."
          else
            echo "::error go.mod or go.sum are not tidy. Please run 'go mod tidy'."
            exit 1
          fi
