---
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    permissions:
      actions: write
      contents: write
      packages: write
      pull-requests: write
    uses: neticdk/shared-github-actions/.github/workflows/go-ci.yaml@199863e78bf5e024e813efba9ecf80642b503930 # v0.6.2
