---
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    permissions:
      actions: write
      contents: write
      packages: write
      pull-requests: write
    uses: neticdk/shared-github-actions/.github/workflows/go-ci.yaml@2220cfb06de98aa5660aa13f8329a34daa73c777 # v0.5.1
